upstars-global/unity-core-modules

- src/helpers/promiseHelpers.ts
- src/services/api/requests/context.ts
- src/store/context.ts
- src/types/clientContext.ts
Added:
- store/context.ts
- services/api/requests/context.ts
- src/helpers/promiseHelpers.ts
- src/types/clientContext.ts
> UN-165: store/context

- src/store/winners.ts
> UN-180: store/winners

- package.json
- src/store/settings.ts
> UN-177: - /store/settings.ts

- src/services/api/DTO/cashbox.ts
- src/services/api/DTO/jackpot.ts
- src/services/api/requests/jackpots.ts
- src/store/jackpots.ts
Added 
- services/api/DTO/jackpot.ts
- services/api/requests/jackpots.ts
- store/jackpots.ts
> UN-156: add jackpots store

- src/controllers/Logger.ts
- src/services/api/requests/sumsub.ts
- src/store/user/userVerificationSumsub.ts
Added:
store/user/userVerificationSumsub.ts
services/api/requests/sumsub.ts
> UN-262: move userVerificationSumsub store

- src/store/user/userGamesHistory.ts
Added: 
- store/user/userGamesHistory.ts
> UN-257: add userGamesHistory store

- src/store/user/userDocuments.ts
Added:
- store/user/userDocuments.ts
> UN-256: add userDocuments store

- src/consts/locales.ts
- src/models/enums/compPoints.ts
- src/models/enums/currencies.ts
- src/models/enums/formFields.ts
- src/models/game.ts
- src/models/lootboxes.ts
- src/services/api/DTO/cashbox.ts
- src/services/api/DTO/couponePromoCodes.ts
- src/services/api/DTO/gifts.ts
- src/services/api/DTO/metrics.ts
- src/services/api/DTO/playerDTO.ts
- src/services/api/requests/metrics.ts
> fix enum imports

- src/services/api/requests/configs.ts
add loadManagersConfigReq to config requests
> add-managers-config

- src/models/PaymentsLib.ts
- src/models/cashbox.ts
- src/models/common.ts
- src/store/cashboxStore.ts
Added:
- src/models/PaymentsLib.ts
- src/models/cashbox.ts
- src/models/common.ts
- src/store/cashboxStore.ts
> UN-163: add cashboxStore

- src/controllers/StagController.ts
- src/controllers/useWelcomePack.ts
- src/helpers/functionsHelper.ts
- src/helpers/jackpotsHelpers.ts
- src/helpers/promoHelpers.ts
- src/helpers/referrerHelper.ts
- src/models/banners.ts
- src/services/localization.service.ts
- src/store/banners.ts
Added:
- src/controllers/StagController.ts
- src/controllers/useWelcomePack.ts
- src/helpers/functionsHelper.ts
- src/helpers/jackpotsHelpers.ts
- src/helpers/referrerHelper.ts
- src/models/banners.ts
- src/store/banners.ts
> UN-162: add banners store

- package.json
- src/controllers/ABTest/ABTestController.ts
- src/controllers/CoveryController.ts
- src/controllers/MetriksController/FullStory.ts
- src/controllers/WebsocketController.ts
- src/controllers/authController.ts
- src/helpers/promiseHelpers.ts
- src/helpers/usePinger.ts
- src/helpers/vipStatusHelper.ts
- src/models/user.ts
- src/services/api/requests/auth.ts
- src/store/auth/auth.ts
- yarn.lock
Added: 
- src/controllers/ABTest/ABTestController.ts
- src/controllers/CoveryController.ts
- src/controllers/MetriksController/FullStory.ts
- src/controllers/WebsocketController.ts
- src/controllers/authController.ts
- src/helpers/usePinger.ts
- src/helpers/vipStatusHelper.ts
- src/store/auth/auth.ts
> UN-152: add auth store

- src/helpers/parseJson.ts
- src/store/achievements.ts
- src/store/tournaments/tournamentsStore.ts
add /store/tournaments/tournamentsStore.ts
> UN-159 move tournaments store to core

- src/helpers/currencyOfCountry.ts
- src/models/enums/currencies.ts
- src/services/api/DTO/current-ip.ts
- src/services/api/requests/common.ts
- src/services/common.ts
- src/store/common.ts
This reverts commit d73a6ff3784c319d9ed2b2c2f1b7996e700e7542.
> Reapply "UN-451 default currency with client's ip (#61)"

- src/controllers/ABTest/ABTestController.ts
- src/controllers/CustomerIO.ts
- src/controllers/MetriksController/FullStory.ts
- src/controllers/MetriksController/GTMController.ts
- src/controllers/MetriksController/HotJar.ts
- src/controllers/MetriksController/MetriksController.ts
- src/controllers/MetriksController/OmniController.ts
- src/controllers/MetriksController/ValdemoroController.ts
- src/controllers/MetriksController/gtmConstants.ts
- src/controllers/MetriksController/pixelCkGRD.ts
- src/controllers/SentryController.ts
- src/controllers/WebsocketController.ts
- src/controllers/authController.ts
- src/helpers/bettingCloseHelper.ts
- src/helpers/bettingHelpers.ts
- src/helpers/vipStatusHelper.ts
- src/services/api/requests/lootbox.ts
- src/store/auth/auth.ts
- src/store/jackpots.ts
- src/store/lootboxes.ts
- src/store/settings.ts
- src/store/winners.ts
Reverts upstars-global/unity-core-modules#79
> Revert "UN-671"

- src/helpers/canonicalHelper.ts
https://upstars.atlassian.net/browse/UN-702
> edit canonicalHelper.ts

- src/services/api/DTO/gifts.ts
- src/services/api/requests/configs.ts
- src/store/gifts.ts
https://upstars.atlassian.net/browse/UN-646
> add modifyGiftsConfig

- src/store/user/userStatuses.ts
> fix: UN-733 move ID_GROUP_FOR_MULTI_ACC to projects configs  (#100)

- src/models/enums/currencies.ts
> fix: add missed GBP currency required in king

- src/helpers/iframeHelpers.ts
- src/helpers/redirectToLang.ts
Added console logs to debug whether the current context is within an iframe and to inspect the message being posted to the parent window. These changes aid in identifying issues during iframe communication.
> UN-605: Add debug logs for iframe message handling

- src/helpers/PromoSorting.ts
This reverts commit 1f92c696736dc63f8074e4d17c3ca9452ff100ae.
> Revert "fet(UN-1154): filter promo identifier with regular expression"

- tests/helpers/achievementHelpers.test.ts
- tests/helpers/bannerHelpers.test.ts
- tests/helpers/currencyHelper.test.ts
- tests/helpers/formErrorMessageHelper.test.ts
- tests/helpers/objectsHelpers.test.ts
- tests/helpers/replaceStringHelper.test.ts
test: add unit tests for achievementHelpers functions
> test: add unit tests for bannerHelpers functions
